robot:
  type: so101_follower
  port: /dev/serial/by-id/usb-1a86_USB_Single_Serial_5B41532613-if00
  id: so101_cong_right
  cameras:
    top:
      type: opencv
      index_or_path: /dev/video12
      width: 640
      height: 480
      fps: 30
    wrist:
      type: opencv
      index_or_path: /dev/video18
      width: 640
      height: 480
      fps: 30
    side:
      type: opencv
      index_or_path: /dev/video14
      width: 640
      height: 480
      fps: 30



dataset:
  repo_id: Ready321/eval_act_pick_redcube_v2
  num_episodes: 10
  single_task: "pick the red cube"
  streaming_encoding: true
  encoder_threads: 2

display_data: true
